### ISSUE TITLE
执行yarn test 报错，执行测试文件路径错误，执行yarn cover，（"cover": "bike --reporter=text"）  无覆盖结果

### ISSUE THREAD

**Issue by wangkris03** [ymzuiku/bike#3]
![image](https://user-images.githubusercontent.com/51576583/128283832-772e67bf-fb30-4b76-9e99-f1c5627c91ce.png)
![image](https://user-images.githubusercontent.com/51576583/128283960-dd76a45f-df04-4550-bff9-4837b7275459.png)

### npx bike --reporter=text
![image](https://user-images.githubusercontent.com/51576583/128285215-6f2d4b17-e9fb-45ad-a894-d94858466f0e.png)

**Comment by ymzuiku** [comment]
fix at bike@0.6.5
