### ISSUE TITLE
Can't use "View test cover" function on Linux

### ISSUE THREAD

**Issue by herosql** [ymzuiku/bike#4]
### "index.ts" code like this:

  ```javascript
export function checkMan(sex: number) {
  if (sex) {
    return true;
  } else {
    return false;
  }
}

export function sayHello(word: string) {
  if (word) {
    console.log(word);
  } else {
    console.log("Hello");
  }
}
```

### "index_test.ts" code like this:
  ```javascript
import { test } from "bike/test";
import { checkMan } from ".";

test.it("index test", (so) => {
  so.deepEqual(21, 21);
});

test.it("test tools isMan:", (so) => {
  so.deepEqual(true, checkMan(1));
});

```

### use "bike --reporter=text" function  result like this:

![Screenshot from 2021-08-05 16-25-54](https://user-images.githubusercontent.com/39084622/128318053-894bbb70-fdf6-4ecd-bced-fa8f2304a60c.png)

**Comment by ymzuiku** [comment]
已修复，现在单独使用 reporter 会进行测试：05b83bebfc29dbd5f8cf805c5e79b7d67aa28aa8
